### ISSUE TITLE
Homeassistant configuration /homeassistant/customize.yaml

### ISSUE THREAD

**Issue by JohnnyPicnic** [MortenVinding/Robomow-ESP32#3]
Hello, thanks for posting this. I have it running but I'm a little confused on setting it up with Home Assistant.
I already have a customize.yaml can I add the contents of your robomow.yaml to my file?
Do I edit all the urls with my ip and credentials? url: "http://<username>:<password>@<IP>/setcmds?250=0"

**Comment by MortenVinding** [comment]
> Hello, thanks for posting this. I have it running but I'm a little confused on setting it up with Home Assistant. I already have a customize.yaml can I add the contents of your robomow.yaml to my file?

Yes I believe you can also add it to customize.yaml
I just prefer to have it in a separate file.

> Do I edit all the urls with my ip and credentials? url: "http://:@/setcmds?250=0"

Yes.
I guess you could put it all in a variable, but I haven’t yet tried it.
Was mostly focused on getting it published so it was ready for the season, and we could start collaborating on it 😊

**Comment by MortenVinding** [comment]
Sorry just realised I made a mistake.
It should have been:

=========================================  
Copy robomow.yaml to config/packages/robomow.yaml
<sub>make dir config/packages if non existent</sub>

Add this to config/configuration.yaml
```
homeassistant:  
  packages: !include_dir_named packages
```
=========================================  

I have updated the README now

**Comment by pergolafabio** [comment]
i see in the packages file, you still use scripts for ble on/off ...
bot there are no scripts , i you created rest commands for it? i think those template switches needs to be changed?

**Comment by pergolafabio** [comment]
nevermind, those scripts are indeed needed, the weekprog on/off for example do more then just the rest commands, they check first if BLE is on/off and stuff like that, i think you forgot to copy/paste them in your package file

i added them now manually

**Comment by PA28T** [comment]
For integration in Home Assistant do you need to install ESPhome first in the ESP32 before uploading the ino/bin file ?  Installing overwrites these.  Is there a preferred procedure?
